spring:
  datasource:
    url: jdbc:mysql://34.227.30.66:3306/mysqldb
    username: mysqladmin
    password: mysqladmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
