spring:
  datasource:
    url: jdbc:mysql://54.164.108.175:3306/mysqldb?useSSL=false
    username: mysqluser
    password: mysqluser
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:        
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        hibernate.show_sql: true
        hibernate.format_sql: true
        hibernate.hbm2ddl.auto: update
