spring:
  datasource:
    url: jdbc:mysql://15.206.69.248:3306/mysqldb
    username: root
    password: Root@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
