spring:
  datasource:
    url: jdbc:mysql://35.154.58.59:3306/mysqldb
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
