spring:
  datasource:
    url: jdbc:mysql://3.88.138.129:3306/mysqldb
    username: mysqldb
    password: mysqldb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
