spring:
  datasource:
    url: jdbc:mysql://13.126.53.159:3306/mysqldb
    username: root
    password: Root@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
