spring:
  datasource:
    url: jdbc:mysql://3.87.214.133:3306/mysqldb
    username: mysqluser
    password: mysqluser
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
