spring:
  datasource:
    url: jdbc:mysql://13.126.245.170:3306/mysqldb
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
