spring:
  datasource:
    url: jdbc:mysql://3.88.210.10:3306/mysqldb
    username: mysqladmin
    password: mysqladmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update

