spring:
  datasource:
    url: jdbc:mysql://52.72.58.42:3306/mysqldb
    username: root
    password: mysqldb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
