spring:
  datasource:
    url: jdbc:mysql://34.207.129.106:3306/mysqldb
    username: mysqladmin
    password: mysqladmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
