spring:
  datasource:
    url: jdbc:mysql://15.206.69.131:3306/mysqldb
    username: awsuser
    password: awsuser
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: create
