spring:
  datasource:
    url: jdbc:mysql://13.235.45.192:3306/mysqldb
    username: mysqluser
    password: mysqluser
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: create
