spring:
  datasource:
    url: jdbc:mysql://13.127.100.225:3306/mysqldb
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: create
