#crud-app-service.yml
apiVersion: v1
kind: Service
metadata:
  name: crud-service
  labels:
    app: crud-app
spec:
  selector:
    app: crud-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
